### ISSUE TITLE
What language and compiler are .lc files ?

### ISSUE THREAD

**Issue by AaronNGray** [cheery/suoml#1]
What language and compiler are .lc files ?

**Comment by cheery** [comment]
They are lever programming language files. The language resembles python.

The grammar is custom grammar file I used with Lever. The language run time
exposed parsing engine as a library.

la 18. heinäk. 2020 klo 21.45 Aaron Gray <notifications@github.com>
kirjoitti:

**Comment by AaronNGray** [comment]
https://github.com/cheery/lever
